colors.draw_bold_text_with_bright_colors = true
# import = [ "~/.config/alacritty/rose-pine.toml" ]
# import = [ "~/.config/alacritty/gruvbox-dark.toml" ]
 import = [ "~/.config/alacritty/nordic.toml" ]

[window]
opacity = 1
dynamic_padding = true

  [window.padding]
  x = 0
  y = 0


  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 16

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold"

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"

[env]
  TERM = "xterm-256color"
