
[colors.primary]
background = "#1a1e24"
foreground = "0xcbced0"

[colors.cursor]
text = "0x1c1e26"
cursor = "0xcbced0"

[colors.normal]
black = "0x1c1e26"
red = "0xe93c58"
green = "0xefaf8e"
yellow = "0xefb993"
blue = "0xdf5273"
magenta = "0xb072d1"
cyan = "0x24a8b4"
white = "0xcbced0"

[colors.bright]
black = "0x6f6f70"
red = "0xe93c58"
green = "0xefaf8e"
yellow = "0xefb993"
blue = "0xdf5273"
magenta = "0xb072d1"
cyan = "0x24a8b4"
white = "0xe3e6ee"

[[colors.indexed_colors]]
index = 16
color = "0xe58d7d"

[[colors.indexed_colors]]
index = 17
color = "0xe4a382"

[[colors.indexed_colors]]
index = 18
color = "0x232530"

[[colors.indexed_colors]]
index = 19
color = "0x2e303e"

[[colors.indexed_colors]]
index = 20
color = "0x9da0a2"

[[colors.indexed_colors]]
index = 21
color = "0xdcdfe4"
